#+TITLE: Miscelánea
#+SUBTITLE: 
#+AUTHOR: 
#+DATE: 
#+SETUPFILE: config.org
#+PROPERTY: header-args :exports code
#+EXPORT_FILE_NAME: misc.pdf


* Lectura de caracteres dentro de un bucle

Cuando se emplea la función =scanf= para leer caracteres de forma repetida (por ejemplo, dentro de un bucle =for= o =while=), hay que escribir un espacio delante de =%c=. Este espacio sirve para descartar la tecla intro que pulsamos después de cada carácter:

#+begin_src C
scanf(" %c")
#+end_src

* Colores

Para escribir letras con colores hay que emplear los denominados "[[https://en.wikipedia.org/wiki/ANSI_escape_code#Description][ANSI escape codes]]". En [[https://stackoverflow.com/questions/3219393/stdlib-and-colored-output-in-c/3219471#3219471][StackOverflow]] se puede encontrar el siguiente ejemplo:


#+begin_src C
#include <stdio.h>

#define ANSI_COLOR_RED     "\x1b[31m"
#define ANSI_COLOR_GREEN   "\x1b[32m"
#define ANSI_COLOR_YELLOW  "\x1b[33m"
#define ANSI_COLOR_BLUE    "\x1b[34m"
#define ANSI_COLOR_MAGENTA "\x1b[35m"
#define ANSI_COLOR_CYAN    "\x1b[36m"
#define ANSI_COLOR_RESET   "\x1b[0m"

int main (int argc, char const *argv[]) {

  printf(ANSI_COLOR_RED     "This text is RED!"     ANSI_COLOR_RESET "\n");
  printf(ANSI_COLOR_GREEN   "This text is GREEN!"   ANSI_COLOR_RESET "\n");
  printf(ANSI_COLOR_YELLOW  "This text is YELLOW!"  ANSI_COLOR_RESET "\n");
  printf(ANSI_COLOR_BLUE    "This text is BLUE!"    ANSI_COLOR_RESET "\n");
  printf(ANSI_COLOR_MAGENTA "This text is MAGENTA!" ANSI_COLOR_RESET "\n");
  printf(ANSI_COLOR_CYAN    "This text is CYAN!"    ANSI_COLOR_RESET "\n");

  return 0;
}
#+end_src


En sistemas Linux y Mac funciona de forma directa. En Windows es necesario instalar [[https://github.com/Microsoft/Terminal#welcome-to-the-windows-terminal-console-and-command-line-repo][Windows Terminal]] y ejecutar el programa desde ahí.

* Limpiar pantalla sin usar =system=

La función =system= (de la librería =stdlib=) permite ejecutar comandos del sistema operativo. Por ejemplo, con =system("cls")= se puede limpiar la pantalla en sistemas Windows. El problema es que el código no es portable (no se puede compilar ni ejecutar en otros sistemas operativos) y, por tanto, se debe evitar su uso. Una solución alternativa es el uso de los "ANSI escape codes" del punto anterior:

#+begin_src C
printf("\x1b[2J");
#+end_src

* Vector de cadenas de caracteres

Una cadena de caracteres es un vector de caracteres. Un vector de cadenas de caracteres (por ejemplo, una lista de textos) se puede pensar como una matriz de caracteres o como un puntero a cadenas de caracteres. Sin embargo, es más sencillo implementarlo mediante un vector de estructuras que tienen un único componente, una cadena de caracteres. 

En el siguiente código se define una estructura que tiene un único componente, una cadena de caracteres. A continuación se define un vector de estructuras, que es, por tanto, un vector de cadenas de caracteres:

#+begin_src C
#include <stdio.h>
#include <stdlib.h>
#define N 5  // Número de cadenas (longitud del vector)

typedef struct
{
  char texto[21];// Cada cadena tiene 20 caracteres max.
} cadena;

int main()
{
  cadena lista[N];
  int i = 0;
  //Lee los textos y los almacena en el vector
  for (i = 0; i < N; i++)
    scanf("%20s", lista[i].texto);
  //Muestra el resultado  
  for (i = 0; i < N; i++)
      printf("%i: %s\n", i, lista[i].texto);

  return 0;  
}
#+end_src

